### ISSUE TITLE
Unable to enable unit testing in vscode

### ISSUE THREAD

**Issue by MohammedUbaid-eaton** [mattrussell2/vscode-cpp-unit-test#2]
![image](https://user-images.githubusercontent.com/96242355/146931590-8b21e3eb-9355-4857-aa67-0a60bfd7e435.png)

First touch command is not recognized, then when definition for touch is added as in:
![image](https://user-images.githubusercontent.com/96242355/146931704-1c2f1c45-c359-4791-9d46-029d5abaf653.png)

Post this, then touch generates another error as:
![image](https://user-images.githubusercontent.com/96242355/146931794-10709d18-b07a-4b10-ae02-efb6b55f4e68.png)

Kindly help me in setting up the extension

**Comment by mattrussell2** [comment]
Looks like you're using PowerShell, which doesn't support 'touch', etc. On windows systems, you might consider Windows Subsystem for Linux: https://docs.microsoft.com/en-us/windows/wsl/install
