### ISSUE TITLE
Using different compiler

### ISSUE THREAD

**Issue by davide-perrone** [mattrussell2/vscode-cpp-unit-test#3]
When I try to run tests using g++ I can change the compiler in the Makefile, but it looks like clang++ is hardcoded elsewhere in the code and the tests do not run. Is this fixable?

**Comment by mattrussell2** [comment]
Great point - updated program to run `make driverFileName` to compile the driver, where `driverFileName` is the variable specified in the configuration [default is `unit_test_driver.o`]. The compiler in your `Makefile` should now be used. Just published an update to that effect (0.4.4)
