### ISSUE TITLE
Invalid syntax error whenever running a test

### ISSUE THREAD

**Issue by asbmeyers** [mattrussell2/vscode-cpp-unit-test#4]
I've tried setting up this extension for unit testing, but every time I try to run any test I get the following error:

```
stdout
------

stderr
------
ERROR: Invalid syntax. Default option is not allowed more than '1' time(s).
Type "TIMEOUT /?" for usage.
```

I've tried setting it up multiple times and I'm fairly certain I've followed the instructions for setting up the extension exactly. I'm using the exact unit_tests.h and Makefile that are shown in the instructions. I have also tried some different test functions (such as simply assert(true)), and they all fail in the same way. It seems the error is related to the timeout command, though I can't find any references to timeout in my code or within the extension.

**Comment by mattrussell2** [comment]
Oh - are you on OSX? I think the timeout command defaults to a BSD variant. See here for an option:

https://stackoverflow.com/questions/3504945/timeout-command-on-mac-os-x

As for where in the code, I think it's currently in line 200 of driverUtils.ts
```
if (timeout) {
        cmd = "timeout --preserve-status " + timeout + " " + cmd;
}
```
