### ISSUE TITLE
Test groups go inside each other

### ISSUE THREAD

**Issue by arttu-karpinlehto** [mattrussell2/vscode-cpp-unit-test#5]
First, thanks!  I have a small project where I wanted to add unit tests and didn't want to add a huge framework.  This extension fit the bill perfectly.

The test group feature works, but it seems that the groups are inserted inside the previous one, see the screenshot.

Also, the closing comment mark is displayed on the testing tree, but that can be fixed by just placing it on the next line.

![image](https://github.com/mattrussell2/vscode-cpp-unit-test/assets/65907494/92c30458-fb0a-4d14-adc1-20cea9115dd8)

**Comment by mattrussell2** [comment]
Glad you like the extension, and great questions! 

Just pushed a fix for both of these in version 0.4.5. 

Now, the */ will be scrubbed from the name; also the test groups will always be at the outer level. 

Let me know if the fix works on your end  :)

Cheers!

**Comment by arttu-karpinlehto** [comment]
It does, thank you!

![image](https://github.com/mattrussell2/vscode-cpp-unit-test/assets/65907494/f7fc86e5-86ab-46e6-814e-bfbdb3829d43)
